version: '3.8'

services:
  sveltekit-app:
    build: .
    ports:
      - "3000:4173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
